language: python
# command to install dependencies

before_install:
    - cd Projects/project_2_packages
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - python -m unittest -v
